// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddglsaqmhmxygskvvqcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkZ2xzYXFtaG14eWdza3Z2cWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzQ3NzYsImV4cCI6MjA2Nzg1MDc3Nn0.F3sUTrRvIVK11cDci_RrMs_7gEN47WwBj78QmHVeMdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});