// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkcbblzskrlfwkkoruuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrY2JibHpza3JsZndra29ydXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjM3MzMsImV4cCI6MjA2NzAzOTczM30.gFBcibVjJyJsdnLTPyxu-XBTjzqMMShcY4ZB1Z9sllU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if we have valid configuration before creating the client
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase configuration. Please check your environment variables.");
}

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

export const supabase = createClient<Database>(
  SUPABASE_URL || "", 
  SUPABASE_PUBLISHABLE_KEY || "", 
  {
    auth: {
      storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);